version: '3.4'
services:
  web:
    build:
      context: .
    hostname: app-api
    container_name: app-api
    command: "python /app/run.py"
    environment:
      TZ: Europe/Paris
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres-data: