version: '3'
services:
  ionic-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8100"

    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

volumes:
    node_modules:

